export const MACHINE = {
    id: 1,
    name: 'main',
    stats: [
        {
            name: 'cpu',
            updateAt: Date.now() - 1000 * 60 * 60,
            total: '100 GB',
            detail: [
                { loaded: 41, usage: '41 GB' },
                { loaded: 56, usage: '56 GB' },
                { loaded: 73, usage: '73 GB' },
                { loaded: 65, usage: '65 GB' },
                { loaded: 48, usage: '48 GB' },
                { loaded: 82, usage: '82 GB' },
                { loaded: 59, usage: '59 GB' },
                { loaded: 44, usage: '44 GB' },
                { loaded: 78, usage: '78 GB' },
                { loaded: 69, usage: '69 GB' },
                { loaded: 47, usage: '47 GB' },
                { loaded: 88, usage: '88 GB' },
                { loaded: 61, usage: '61 GB' },
                { loaded: 53, usage: '53 GB' },
                { loaded: 71, usage: '71 GB' },
                { loaded: 84, usage: '84 GB' },
                { loaded: 57, usage: '57 GB' },
                { loaded: 66, usage: '66 GB' },
                { loaded: 49, usage: '49 GB' },
                { loaded: 90, usage: '90 GB' },
                { loaded: 43, usage: '43 GB' },
                { loaded: null, usage: '75 GB' },
                { loaded: null, usage: '58 GB' },
                { loaded: null, usage: '62 GB' },
                { loaded: 80, usage: '80 GB' },
                { loaded: 68, usage: '68 GB' },
                { loaded: 87, usage: '87 GB' },
                { loaded: 52, usage: '52 GB' },
                { loaded: 45, usage: '45 GB' },
                { loaded: 70, usage: '70 GB' },
                { loaded: 79, usage: '79 GB' },
                { loaded: 63, usage: '63 GB' },
                { loaded: 54, usage: '54 GB' },
                { loaded: 46, usage: '46 GB' },
                { loaded: 74, usage: '74 GB' },
                { loaded: 83, usage: '83 GB' },
                { loaded: 42, usage: '42 GB' },
                { loaded: 60, usage: '60 GB' },
                { loaded: 85, usage: '85 GB' },
                { loaded: 72, usage: '72 GB' },
                { loaded: 50, usage: '50 GB' },
                { loaded: 67, usage: '67 GB' },
                { loaded: 76, usage: '76 GB' },
                { loaded: 55, usage: '55 GB' },
                { loaded: 81, usage: '81 GB' },
                { loaded: 64, usage: '64 GB' },
                { loaded: 86, usage: '86 GB' },
                { loaded: 77, usage: '77 GB' },
                { loaded: 89, usage: '89 GB' },
                { loaded: 80, usage: '80 GB' },
            ],
        },
        {
            name: 'memory',
            updateAt: Date.now() - 1000 * 60 * 60,
            total: '100 GB',
            detail: [
                { loaded: 20, usage: '41 GB' },
                { loaded: 56, usage: '56 GB' },
                { loaded: 73, usage: '73 GB' },
                { loaded: 65, usage: '65 GB' },
                { loaded: 48, usage: '48 GB' },
                { loaded: 82, usage: '82 GB' },
                { loaded: 59, usage: '59 GB' },
                { loaded: 44, usage: '44 GB' },
                { loaded: 78, usage: '78 GB' },
                { loaded: 69, usage: '69 GB' },
                { loaded: 47, usage: '47 GB' },
                { loaded: 88, usage: '88 GB' },
                { loaded: 61, usage: '61 GB' },
                { loaded: 53, usage: '53 GB' },
                { loaded: 71, usage: '71 GB' },
                { loaded: 84, usage: '84 GB' },
                { loaded: 34, usage: '57 GB' },
                { loaded: 25, usage: '66 GB' },
                { loaded: 49, usage: '49 GB' },
                { loaded: 90, usage: '90 GB' },
                { loaded: 43, usage: '43 GB' },
                { loaded: 3, usage: '75 GB' },
                { loaded: 67, usage: '58 GB' },
                { loaded: null, usage: '62 GB' },
                { loaded: 80, usage: '80 GB' },
                { loaded: 68, usage: '68 GB' },
                { loaded: 69, usage: '87 GB' },
                { loaded: 52, usage: '52 GB' },
                { loaded: 45, usage: '45 GB' },
                { loaded: null, usage: '70 GB' },
                { loaded: 79, usage: '79 GB' },
                { loaded: 63, usage: '63 GB' },
                { loaded: 54, usage: '54 GB' },
                { loaded: 46, usage: '46 GB' },
                { loaded: 74, usage: '74 GB' },
                { loaded: 83, usage: '83 GB' },
                { loaded: 42, usage: '42 GB' },
                { loaded: 65, usage: '60 GB' },
                { loaded: 85, usage: '85 GB' },
                { loaded: 72, usage: '72 GB' },
                { loaded: 50, usage: '50 GB' },
                { loaded: 67, usage: '67 GB' },
                { loaded: 76, usage: '76 GB' },
                { loaded: 55, usage: '55 GB' },
                { loaded: 81, usage: '81 GB' },
                { loaded: 64, usage: '64 GB' },
                { loaded: 86, usage: '86 GB' },
                { loaded: 77, usage: '77 GB' },
                { loaded: 89, usage: '89 GB' },
                { loaded: 2, usage: '40 GB' },
            ],
        },
        {
            name: 'hard',
            updateAt: Date.now() - 1000 * 60 * 60,
            total: '100 GB',
            detail: [
                { loaded: 41, usage: '41 GB' },
                { loaded: 56, usage: '56 GB' },
                { loaded: 73, usage: '73 GB' },
                { loaded: 65, usage: '65 GB' },
                { loaded: 48, usage: '48 GB' },
                { loaded: 82, usage: '82 GB' },
                { loaded: 59, usage: '59 GB' },
                { loaded: 44, usage: '44 GB' },
                { loaded: 78, usage: '78 GB' },
                { loaded: 69, usage: '69 GB' },
                { loaded: 47, usage: '47 GB' },
                { loaded: 67, usage: '88 GB' },
                { loaded: 61, usage: '61 GB' },
                { loaded: 53, usage: '53 GB' },
                { loaded: 71, usage: '71 GB' },
                { loaded: 84, usage: '84 GB' },
                { loaded: 57, usage: '57 GB' },
                { loaded: 66, usage: '66 GB' },
                { loaded: 49, usage: '49 GB' },
                { loaded: 90, usage: '90 GB' },
                { loaded: 43, usage: '43 GB' },
                { loaded: null, usage: '75 GB' },
                { loaded: 2, usage: '58 GB' },
                { loaded: null, usage: '62 GB' },
                { loaded: 80, usage: '80 GB' },
                { loaded: 43, usage: '68 GB' },
                { loaded: 87, usage: '87 GB' },
                { loaded: 52, usage: '52 GB' },
                { loaded: 45, usage: '45 GB' },
                { loaded: null, usage: '70 GB' },
                { loaded: 79, usage: '79 GB' },
                { loaded: 63, usage: '63 GB' },
                { loaded: 54, usage: '54 GB' },
                { loaded: 46, usage: '46 GB' },
                { loaded: 74, usage: '74 GB' },
                { loaded: 83, usage: '83 GB' },
                { loaded: 42, usage: '42 GB' },
                { loaded: 60, usage: '60 GB' },
                { loaded: 85, usage: '85 GB' },
                { loaded: 72, usage: '72 GB' },
                { loaded: 50, usage: '50 GB' },
                { loaded: 67, usage: '67 GB' },
                { loaded: 76, usage: '76 GB' },
                { loaded: 55, usage: '55 GB' },
                { loaded: 81, usage: '81 GB' },
                { loaded: 64, usage: '64 GB' },
                { loaded: 86, usage: '86 GB' },
                { loaded: 77, usage: '77 GB' },
                { loaded: 89, usage: '89 GB' },
                { loaded: 40, usage: '40 GB' },
            ],
        },
    ],
};
