[package]
name = "dideban"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
directories = "6.0.0"
toml = "0.9.2"
actix-web = "4"
log = { version = "0.4", features = ["std"] }
chrono = "0.4.41"
colored = "3.0.0"
